CREATE TABLE bird_strike (
  id int NOT NULL,
  airport text,
  aircraft text,
  num_strikes int,
  flight_effect text,
  flight_date text,
  damage_effect text,
  airline text,
  origin_state text,
  flight_phase text,
  precipitation_conditions text,
  wildlife_remains_collected boolean,
  remarks text,
  wildlife_size text,
  sky_conditions text,
  wildlife_species text,
  pilot_warned boolean,
  cost int,
  altitude int,
  num_injured int,
  large_aircraft boolean,
  PRIMARY KEY (id)
);

COPY bird_strike(id,
  airport,
  aircraft,
  num_strikes,
  flight_effect,
  flight_date,
  damage_effect,
  airline,
  origin_state,
  flight_phase,
  precipitation_conditions,
  wildlife_remains_collected,
  remarks,
  wildlife_size,
  sky_conditions,
  wildlife_species,
  pilot_warned,
  cost,
  altitude,
  num_injured,
  large_aircraft)
FROM '/docker-entrypoint-initdb.d/bird_strikes.csv'
DELIMITER ','
NULL '' CSV;