const LOCAL = false
export const BACKEND_URL = LOCAL ? "http://localhost:3001" : "http://3.16.78.249:3001";
export const INCIDENTS_PER_AIRCRAFT_API = BACKEND_URL + "/incidents-per-aircraft";
export const INCIDENTS_BY_YEAR_API = BACKEND_URL + "/incidents-by-year";
export const INCIDENTS_BY_MONTH_API = BACKEND_URL + "/incidents-by-month";
export const INCIDENTS_BY_FLIGHT_PATH_API = BACKEND_URL + "/incidents-by-flight-path";
export const INCIDENTS_BY_AIRLINE_API = BACKEND_URL + "/incidents-by-airline";
export const DATAPOINTS_BY_YEAR_API = BACKEND_URL + "/datapoints-by-year/";
export const FATALITY_RATE = BACKEND_URL + "/fatality-rate";
export const TOTAL_INCIDENTS = BACKEND_URL + "/total-incidents";
